/* Generated By:JavaCC: Do not edit this line. JJTreeParserTreeConstants.java Version 5.0 */
package com.javadoq.jjtree;

public interface JJTreeParserTreeConstants
{
  public int JJTGRAMMAR = 0;
  public int JJTVOID = 1;
  public int JJTCOMPILATIONUNIT = 2;
  public int JJTPACKAGENAME = 3;
  public int JJTIMPORTNAME = 4;
  public int JJTNEWNAME = 5;
  public int JJTNEWTYPE = 6;
  public int JJTSUPERLIST = 7;
  public int JJTNAME = 8;


  public String[] jjtNodeName = {
    "Grammar",
    "void",
    "CompilationUnit",
    "PackageName",
    "ImportName",
    "NewName",
    "NewType",
    "SuperList",
    "Name",
  };
}
/* JavaCC - OriginalChecksum=bd733323f7edc882d503b563db49055c (do not edit this line) */
