/* Generated By:JJTree: Do not edit this line. ASTCompilationUnit.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.javadoq.javadoc;

public
class ASTCompilationUnit extends ASTNode {
  public ASTCompilationUnit(int id) {
    super(id);
  }

  public ASTCompilationUnit(JavadocParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8700a5db7fad756edd12327e0cbb8e57 (do not edit this line) */
