/* Generated By:JavaCC: Do not edit this line. JavadocParserTreeConstants.java Version 5.0 */
package com.javadoq.javadoc;

public interface JavadocParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTVOID = 1;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "void",
  };
}
/* JavaCC - OriginalChecksum=22c17f492df04b0b2888e1c9477e3056 (do not edit this line) */
